# Generated by Django 4.2 on 2024-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimer',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktimer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
